baseURL: https://carlf.io
languageCode: en-us
title: carlf.io
theme: github.com/carlf/hugo-theme-olympus

markup:
  highlight:
    guessSyntax: true
    style: nord

params:
  author: Carl Flippin

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags
      weight: 3

module:
  imports:
  - path: github.com/carlf/hugo-theme-olympus
