baseURL: https://carlf.io
languageCode: en-us
title: carlf.io
theme: github.com/vaga/hugo-theme-m10c

markup:
  highlight:
    guessSyntax: true
    style: nord

params:
  author: Carl Flippin
  description: I'm just as confused as the rest of you
  avatar: avatar.png
  social:
    - icon: github
      name: "My Github"
      url: https://github.com/carlf
    - icon: key
      name: "My GPG Key"
      url: https://keyoxide.org/50f1a8d452b5c094a656ce6aac084c5eec19856d
    - icon: rss
      name: RSS
      url: https://carlf.io/index.xml
  style:
    darkestColor: "#2e3440"
    darkColor: "#3b4252"
    lightColor: "#d8dee9"
    lightestColor: "#eceff4"
    primaryColor: "#81a1c1"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: categories
      name: Categories
      url: /categories
      weight: 2

module:
  imports:
    - path: github.com/vaga/hugo-theme-m10c
