baseURL: https://carlf.io
languageCode: en-us
title: "Carl's Blog"
defaultContentLanguage: en
theme: github.com/joway/hugo-theme-yinyang

markup:
  highlight:
    guessSyntax: true
    noClasses: true
    style: bw
    tabWidth: 2

author:
  name: "Carl Flippin"
  homepage: https://carlf.io

params:
  description: "Laziness, Impatience, Hubris"
  mainSections:
    - posts
  socials:
    - name: Github
      link: https://github.com/carlf
    - name: LinkedIn
      link: https://www.linkedin.com/in/carlflippin/
    - name: RSS
      link: /index.xml
  extraCSSFiles: ["css/extra.css"]

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags
      weight: 3

module:
  imports:
  - path: github.com/joway/hugo-theme-yinyang
